name:                 z-a4-z-part2and3
version:              0.1.0.0
package-name:         a4
lib-name:             part2and3
id:                   a4-0.1.0.0-inplace-part2and3
key:                  a4-0.1.0.0-inplace-part2and3
abi:                  inplace
exposed-modules:      Infer InferMonad Term Type TypeCheck Unify
import-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a4-0.1.0.0/l/part2and3/build/part2and3

library-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a4-0.1.0.0/l/part2and3/build/part2and3

library-dirs-static:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a4-0.1.0.0/l/part2and3/build/part2and3

dynamic-library-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a4-0.1.0.0/l/part2and3/build/part2and3

data-dir:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/.

hs-libraries:         HSa4-0.1.0.0-inplace-part2and3
depends:              base-4.20.1.0-276c containers-0.7-c939 mtl-2.3.1-080f
haddock-interfaces:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a4-0.1.0.0/l/part2and3/doc/html/a4/part2and3.haddock

haddock-html:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a4-0.1.0.0/l/part2and3/doc/html/a4
