name:                 z-a4-z-part1
version:              0.1.0.0
package-name:         a4
lib-name:             part1
id:                   a4-0.1.0.0-inplace-part1
key:                  a4-0.1.0.0-inplace-part1
abi:                  inplace
exposed-modules:      Imperative
import-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a4-0.1.0.0/l/part1/build/part1

library-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a4-0.1.0.0/l/part1/build/part1

library-dirs-static:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a4-0.1.0.0/l/part1/build/part1

dynamic-library-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a4-0.1.0.0/l/part1/build/part1

data-dir:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/.

hs-libraries:         HSa4-0.1.0.0-inplace-part1
depends:              base-4.20.1.0-276c containers-0.7-c939 mtl-2.3.1-080f
haddock-interfaces:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a4-0.1.0.0/l/part1/doc/html/a4/part1.haddock

haddock-html:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a4-starter-files-wodugesi/a4-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a4-0.1.0.0/l/part1/doc/html/a4
