name:                 z-a2-z-higher-order-functions
version:              0.1.0.0
package-name:         a2
lib-name:             higher-order-functions
id:                   a2-0.1.0.0-inplace-higher-order-functions
key:                  a2-0.1.0.0-inplace-higher-order-functions
abi:                  inplace
exposed-modules:      HigherOrderFunctions
import-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a2-0.1.0.0/l/higher-order-functions/build/higher-order-functions

library-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a2-0.1.0.0/l/higher-order-functions/build/higher-order-functions

library-dirs-static:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a2-0.1.0.0/l/higher-order-functions/build/higher-order-functions

dynamic-library-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a2-0.1.0.0/l/higher-order-functions/build/higher-order-functions

data-dir:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/.

hs-libraries:         HSa2-0.1.0.0-inplace-higher-order-functions
depends:              base-4.20.1.0-276c containers-0.7-c939 mtl-2.3.1-080f
haddock-interfaces:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a2-0.1.0.0/l/higher-order-functions/doc/html/a2/higher-order-functions.haddock

haddock-html:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a2-0.1.0.0/l/higher-order-functions/doc/html/a2
