name:                 z-a2-z-evaluator
version:              0.1.0.0
package-name:         a2
lib-name:             evaluator
id:                   a2-0.1.0.0-inplace-evaluator
key:                  a2-0.1.0.0-inplace-evaluator
abi:                  inplace
exposed-modules:      BigStep DeBruijn SmallStep Term
import-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a2-0.1.0.0/l/evaluator/build/evaluator

library-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a2-0.1.0.0/l/evaluator/build/evaluator

library-dirs-static:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a2-0.1.0.0/l/evaluator/build/evaluator

dynamic-library-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a2-0.1.0.0/l/evaluator/build/evaluator

data-dir:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/.

hs-libraries:         HSa2-0.1.0.0-inplace-evaluator
depends:              base-4.20.1.0-276c containers-0.7-c939 mtl-2.3.1-080f
haddock-interfaces:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a2-0.1.0.0/l/evaluator/doc/html/a2/evaluator.haddock

haddock-html:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a2-starter-files-wodugesi/a2-starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a2-0.1.0.0/l/evaluator/doc/html/a2
