cabal-version:      3.0
name:               a2
version:            0.1.0.0
build-type:         Simple

common warnings
    ghc-options: -Wall

library evaluator
  import:           warnings
  exposed-modules:
      DeBruijn
      SmallStep
      BigStep
      Term
  hs-source-dirs:
      .
  build-depends:    containers >=0.6.4.1,
                    base >=4.15.1.0,
                    mtl
  default-language: Haskell2010

library higher-order-functions
  import:           warnings
  exposed-modules:
      HigherOrderFunctions
  hs-source-dirs:
      .
  build-depends:    containers >=0.6.4.1,
                    base >=4.15.1.0,
                    mtl
  default-language: Haskell2010

test-suite higher-order-functions-tests
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          HigherOrderFunctionsTests.hs
    build-depends:    base >=4.15.1.0,
                      evaluator,
                      higher-order-functions,
                      tasty >=1.4.2.3,
                      tasty-hunit >=0.10.0.3,
                      tasty-quickcheck >=0.10.2,
    other-modules:
    hs-source-dirs:   test
    default-language: Haskell2010

test-suite removeNames-tests
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          RemoveNamesTests.hs
    build-depends:    base >=4.15.1.0,
                      evaluator,
                      higher-order-functions,
                      tasty >=1.4.2.3,
                      tasty-hunit >=0.10.0.3,
                      tasty-quickcheck >=0.10.2,
    other-modules:
    hs-source-dirs:   test
    default-language: Haskell2010

test-suite shifting-tests
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          ShiftingTests.hs
    build-depends:    base >=4.15.1.0,
                      evaluator,
                      higher-order-functions,
                      tasty >=1.4.2.3,
                      tasty-hunit >=0.10.0.3,
                      tasty-quickcheck >=0.10.2,
    other-modules:
    hs-source-dirs:   test
    default-language: Haskell2010

test-suite subst-tests
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          SubstTests.hs
    build-depends:    base >=4.15.1.0,
                      evaluator,
                      higher-order-functions,
                      tasty >=1.4.2.3,
                      tasty-hunit >=0.10.0.3,
                      tasty-quickcheck >=0.10.2,
    other-modules:
    hs-source-dirs:   test
    default-language: Haskell2010

test-suite small-step-tests
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          SmallStepTests.hs
    build-depends:    base >=4.15.1.0,
                      evaluator,
                      higher-order-functions,
                      tasty >=1.4.2.3,
                      tasty-hunit >=0.10.0.3,
                      tasty-quickcheck >=0.10.2,
    other-modules:
    hs-source-dirs:   test
    default-language: Haskell2010

test-suite big-step-tests
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          BigStepTests.hs
    build-depends:    base >=4.15.1.0,
                      evaluator,
                      higher-order-functions,
                      tasty >=1.4.2.3,
                      tasty-hunit >=0.10.0.3,
                      tasty-quickcheck >=0.10.2,
    other-modules:
    hs-source-dirs:   test
    default-language: Haskell2010
