name:                 z-a1-z-evaluator
version:              0.1.0.0
package-name:         a1
lib-name:             evaluator
id:                   a1-0.1.0.0-inplace-evaluator
key:                  a1-0.1.0.0-inplace-evaluator
abi:                  inplace
exposed-modules:      BigStep SmallStep Term
import-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a1-starter-files-wodugesi/starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a1-0.1.0.0/l/evaluator/build/evaluator

library-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a1-starter-files-wodugesi/starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a1-0.1.0.0/l/evaluator/build/evaluator

library-dirs-static:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a1-starter-files-wodugesi/starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a1-0.1.0.0/l/evaluator/build/evaluator

dynamic-library-dirs:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a1-starter-files-wodugesi/starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a1-0.1.0.0/l/evaluator/build/evaluator

data-dir:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a1-starter-files-wodugesi/starter/.

hs-libraries:         HSa1-0.1.0.0-inplace-evaluator
depends:              base-4.20.1.0-276c containers-0.7-c939 mtl-2.3.1-080f
haddock-interfaces:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a1-starter-files-wodugesi/starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a1-0.1.0.0/l/evaluator/doc/html/a1/evaluator.haddock

haddock-html:
    /h/u14/c1/00/wodugesi/Documents/CSC324---Principles-of-Programming-Languages/a1-starter-files-wodugesi/starter/dist-newstyle/build/x86_64-linux/ghc-9.10.2/a1-0.1.0.0/l/evaluator/doc/html/a1
